name: showcase_cicd_snowflake

# Controls when the action will run. 
on:
  push:
    branches:
      - main
    paths:
      - 'dbscripts/**' 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  snowflake-cicd-showcase:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Python 3.8.x
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8.x

      - name: Run Python Script
        run: |
         python dbscripts/sid.py
