name: showcase_cicd_snowflake

# Controls when the action will run. 
on:
  push:
    branches:
      - main
    paths:
      - 'dbscripts/**' 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  snowflake-cicd-showcase:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      

      - name: Check Versioning Conventions and Underscores
        run: |
          for file in $(find . -name '*.sql'); do
            # Check if the filename follows versioning conventions (e.g., v1.0.0__insert_script.sql)
            if ! [[ $(basename "$file") =~ ^V\d+\.\d+\.\d+__[a-zA-Z0-9_]+\.sql$ ]]; then
              echo "Error: Invalid versioning convention in file $file"
              exit 1
            fi

            # Check if the filename contains underscores
            #if [[ $(basename "$file") != *_* ]]; then
              #echo "Error: Underscores are required in the filename for file $file"
              #exit 1
           # fi
          done

      - name: Database Schema Change and Deployment
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          python --version
          echo "Step 1: Installing schemachange"
          pip install schemachange
          
          
          
          echo "Step 2: Running schemachange"
          schemachange -f $GITHUB_WORKSPACE/dbscripts -a $SF_ACCOUNT -u $SF_USERNAME -r $SF_ROLE -w $SF_WAREHOUSE -d $SF_DATABASE -c $SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-tablea
