          echo "Step 2: Running schemachange"

          # Run schemachange for files matching the pattern
          for file in $GITHUB_WORKSPACE/dbscripts/*; do
            if [[ $file =~ [vV][0-9]+\.[0-9]+\.[0-9]+__[a-zA-Z0-9_]+\.sql$ ]]; then
              echo "Processing file: $file"
              schemachange -f "$file" -a $SF_ACCOUNT -u $SF_USERNAME -r $SF_ROLE -w $SF_WAREHOUSE -d $SF_DATABASE -c $SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table --root-folder $GITHUB_WORKSPACE
            else
              echo "Skipping file: $file"
            fi
          done
