name: showcase_cicd_snowflake

# Controls when the action will run. 
on:
  push:
    branches:
      - main
    paths:
      - 'dbscripts/**' 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  snowflake-cicd-showcase:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Python 3.8.x
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8.x

      - name: Run schemachange
        env:
          SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SF_ROLE: ${{ secrets.SF_ROLE }}
          SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
          SF_DATABASE: ${{ secrets.SF_DATABASE }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          python --version
          echo "Step 1: Installing schemachange"
          pip install schemachange

          echo "Step 2: Running schemachange"
          # Run schemachange for files matching the pattern
          find $GITHUB_WORKSPACE/dbscripts -type f -regex '.*[vV]\d+\.\d+\.\d+__[a-zA-Z0-9_]+\.sql$' | while read -r file; do
            echo "Processing file: $file"
            schemachange -f "$file" -a $SF_ACCOUNT -u $SF_USERNAME -r $SF_ROLE -w $SF_WAREHOUSE -d $SF_DATABASE -c $SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table
          done

          # Print files that do not match the pattern
          find $GITHUB_WORKSPACE/dbscripts -type f ! -regex '.*[vV]\d+\.\d+\.\d+__[a-zA-Z0-9_]+\.sql$' | while read -r file; do
            echo "File does not match the pattern: $file"
          done
