name: Run Schemachange

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  run_schemachange:
    runs-on: ubuntu-latest

    env:
      SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
      SF_USERNAME: ${{ secrets.SF_USERNAME }}
      SF_ROLE: ${{ secrets.SF_ROLE }}
      SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
      SF_DATABASE: ${{ secrets.SF_DATABASE }}
      SF_PASSWORD: ${{ secrets.SF_PASSWORD }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Adjust the Python version as needed

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install schemachange

    - name: Run Python Script
      run: |
        python - <<EOF
import os
import re
import subprocess

directory = "dbscripts/"
pattern = r"^[vV]\d+\.\d+\.\d+__[a-zA-Z0-9_]+\.sql$"

# Use os.scandir to get a list of files in the directory
for entry in os.scandir(directory):
    if entry.is_file():
        # Extract the file name from the full path
        file_name = entry.name
        print(file_name)

        # Check if the file name matches the pattern
        if re.match(pattern, file_name):
            print(f"File '{file_name}' matches the pattern. Proceeding with schemachange.")

            # Add schemachange logic here
            schemachange_command = (
                f"schemachange -f {directory} -a {os.environ['SF_ACCOUNT']} -u {os.environ['SF_USERNAME']} "
                f"-r {os.environ['SF_ROLE']} -w {os.environ['SF_WAREHOUSE']} -d {os.environ['SF_DATABASE']} "
                f"-c {os.environ['SF_DATABASE']}.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table"
            )
            subprocess.run(schemachange_command, shell=True, check=True)
            
        else:
            print(f"File '{file_name}' does not match the pattern. Skipping schemachange.")
            # Skip schemachange for files that do not match the pattern
            continue
EOF
